# Generated by Django 2.1 on 2019-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='failed_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField()),
                ('error', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField()),
                ('keywords', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
