# Generated by Django 2.1 on 2019-08-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='failed_news',
            table='failed_news',
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
